# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
    jdkVersionOption: 1.11
    goals: 'clean package'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'target/spring-petclinic-2.4.5.jar'
    TargetPath: 'app.jar'
    ArtifactName: 'drop'
    publishLocation: 'Container'
